language: python
python:
  - "2.7"
env:
  global:
    - SC_SOURCE_URL="https://gist.githubusercontent.com/henrikhodne/9322897/raw/sauce-connect.sh"
    - secure: |-
        CMKR45ew7fJWfF/rvaFkV4gNhWRDdM4y8wlj5p1qrEzJ214SENg03fjHJr6B
        cvNf7vanTJKnVxpxUK9kH5Tn/uaJZtnbnJYehZ4YKwzbJQEAEJpWvCk4C54O
        7diAxOq7YSxxqA2XdtLydkNlo85BWoucmc0yHEl3weNR9554UmM=
    - secure: |-
        WmE7J5Vxheir50Heuji0JVpEmoYH5iPkLMQFgnocY1UspO1ka1+8M7SOgsUH
        SK5yLKZ/6oJyhlySqqTmCfYy3y/WXRNG76dy1kjVj/DEbx+n6Yu0nElw84ED
        ZR5KkpFMaKLA505soY+4lJc4jRl5u0qwCB1Ad3UgTgfkI4QSaGM=
    - PATH="/usr/share/elasticsearch/bin:/usr/lib/postgresql/9.3/bin:$PATH"
  matrix:
    - BROWSER=
    - BROWSER=Chrome
before_install:
  - whereis elasticsearch
  - sudo service postgresql stop
  - postgres --version
  - initdb --version
  - sudo service elasticsearch stop
  - elasticsearch -v
install:
  - python bootstrap.py -v 2.2.5
  - bin/buildout -c buildout-travis.cfg
before_script:
  - if test -n "$BROWSER"; then curl -L "$SC_SOURCE_URL" | bash; fi
script:
  - if test -z "$BROWSER"; then npm test; fi
  - if test -z "$BROWSER"; then bin/test -v -v --timeout=200 -m "not bdd"; fi
  - >
    if test -n "$BROWSER"; then
      bin/test -v -v --timeout=200 --remote-webdriver -m "bdd" --tb=short \
        --browser-arg url "http://$SAUCE_USERNAME:$SAUCE_ACCESS_KEY@localhost:4445/wd/hub" \
        --browser-arg tunnel-identifier "$TRAVIS_JOB_NUMBER" \
        --browser-arg-int build  "$TRAVIS_BUILD_NUMBER" \
        --browser-arg name "$TRAVIS_REPO_SLUG $TRAVIS_BRANCH $TRAVIS_COMMIT" \
        --browser-arg-int wait_time 10 \
        --browser "$BROWSER"
    fi
after_script:
  - >
    if test -n "$BROWSER"; then
      SAUCE_JOB_ID=`grep -m 1 /session/ "$HOME/sauce-connect.log" | cut -d / -f 7`
      SAUCE_PASSED=`((TRAVIS_TEST_RESULT == 0)) && echo true || echo false`
      curl -H "Content-Type:text/json" -s -X PUT -d "{\"passed\": $SAUCE_PASSED}" \
        "http://$SAUCE_USERNAME:$SAUCE_ACCESS_KEY@saucelabs.com/rest/v1/$SAUCE_USERNAME/jobs/$SAUCE_JOB_ID"
      echo "Sauce test page https://saucelabs.com/tests/$SAUCE_JOB_ID"
    fi
