language: python
python:
  - "2.7"
env: 
  global: 
  - secure: |-
      t+lPD6JK4y285juflyou+HGLAbDCRblpfabQQC+klC1iArbvqAmjJB8NdrNy
      SUSM7e4U5KwvCCxCbOv6p9FCMbgzDfYWQcvsKYeDyo0IuuoqasSqAbN5lPVC
      XjdIE6vlGoLpWf0CHZ1wONXGv6E6VISpdbInd0S3R998qNK774g=
  - secure: |-
      WmE7J5Vxheir50Heuji0JVpEmoYH5iPkLMQFgnocY1UspO1ka1+8M7SOgsUH
      SK5yLKZ/6oJyhlySqqTmCfYy3y/WXRNG76dy1kjVj/DEbx+n6Yu0nElw84ED
      ZR5KkpFMaKLA505soY+4lJc4jRl5u0qwCB1Ad3UgTgfkI4QSaGM=
before_install:
  - sudo apt-get -qq --purge remove postgresql postgresql-9.1
  - source /etc/lsb-release
  - echo "deb http://apt.postgresql.org/pub/repos/apt/ $DISTRIB_CODENAME-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
  - curl http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get -qq -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" install postgresql-9.2 libpq-dev
  - sudo /etc/init.d/postgresql start
install:
  - python bootstrap.py
  - bin/buildout
before_script:
  - sudo -u postgres createuser $USER
  - sudo -u postgres createdb --owner=$USER encoded
  - "curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash"
script: |-
  bin/test -v -v --timeout=200 --remote-webdriver \
  --engine-url postgresql:///encoded \
  --browser-arg url "http://$SAUCE_USERNAME:$SAUCE_ACCESS_KEY@localhost:4445/wd/hub" \
  --browser-arg tunnel-identifier "$TRAVIS_JOB_NUMBER" \
  --browser-arg-int wait_time 5
