language: python
python:
  - "2.7"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install: "python bootstrap.py && bin/buildout"
script: "bin/test -v -v -s --timeout=200"
