#cloud-config
#
# Use ubuntu-raring-13.04-amd64-server-20130928 (ami-5e03e429) not the default
# Ubuntu 13.04 image to ensure cloud-init runs the runcmd steps.

# Debug log
output: {all: '| tee -a /var/log/cloud-init-output.log'}

package_upgrade: true
packages:
- build-essential
- apache2-mpm-event
- elasticsearch
- envdir
- git
- libapache2-mod-wsgi
- libevent-dev
- libfreetype6-dev
- libjpeg-dev
- libmagic-dev
- libpq-dev
- libssl-dev
- libxml2-dev
- libxslt1-dev
- lzop
- mysql-devel
- npm
- postgresql-9.3
- pv
- python2.7-dev
- python-virtualenv
- ruby-dev
- zlib1g-dev

users:
- default
- name: encoded
  gecos: ENCODE Metadata Database daemon user
  inactive: true
  system: true
  # Specified homedir must exist
  # https://github.com/rubygems/rubygems/issues/689
  homedir: /srv/encoded

runcmd:
# Ideally this would build as a different user so encoded only has read
# permissions
- set -e
- sudo -u postgres createuser encoded
- sudo -u postgres createdb --owner=encoded encoded
- mkdir /srv/encoded
- chown encoded:encoded /srv/encoded
- cd /srv/encoded
- sudo -u encoded git clone https://github.com/ENCODE-DCC/encoded.git .
- sudo -u encoded python2.7 bootstrap.py
- sudo -u encoded bin/buildout
- ln -s /srv/encoded/etc/encoded-apache.conf /etc/apache2/sites-available/encoded
- a2ensite encoded
- a2dissite default
- service apache2 reload

## Import ssh keys from launchpad:
# ssh_import_id:
# - lrowe

## Or specify public keys:
ssh_authorized_keys:
- ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA4cGlJUDTeX7QHvJ6AHbRKqgXihkooOTtct/JGkNfOIf/0ATG4TlXhDALk7ixUuaQQHTeHFYPnAKCu04ngRRnWUPh1Rjhpgr/DDWoAOw8cQyHs8x4qXW0+RSsE9w+OGACj2JtqpZ/RBrj3ymOrHx6BEepz+6waKb3nEw3eeGSmBGOjq0/Z2iKVPS/vmB33UJLwQu+JoalRR/I1ocCsUTHS756o1tH5zsz8ZSpnAe978vctqGPoc1N8y+U/YHQHLJMtBQnstmVWfNYEen10UhVosUmSxLiPkSEc606HzO6eQN3qjPRFq6ICbifV3jRBBSkzW9uwsEqNc4A4YXQIV2Eew== encoded@demo-a.encodedcc.org

apt_sources:
# This is not quite the latest version
# https://github.com/elasticsearch/elasticsearch/issues/3286
- source: "deb http://ppa.launchpad.net/nickstenning/elasticsearch/ubuntu precise main"
  key: |
    -----BEGIN PGP PUBLIC KEY BLOCK-----
    Version: SKS 1.1.4
    Comment: Hostname: keyserver.ubuntu.com

    mI0EUXlz4AEEAL+X7FwxmWhmq+DyZCamSU5HaXziZnXuM0GsKXqEWm7uNRvMYdIstCYTjAav
    +bisIyFTj7JXCI20K5uIc8ZPl2wPY+YWM71mnfSZmi3zg13rF3NJN18UyW2tb1aP5XtdVQ+r
    R/IPFPzJ0Z3n4aNCLM1M6+BmZVWsZZeqHe6x0AkZABEBAAG0H0xhdW5jaHBhZCBQUEEgZm9y
    IE5pY2sgU3Rlbm5pbmeIuAQTAQIAIgUCUXlz4AIbAwYLCQgHAwIGFQgCCQoLBBYCAwECHgEC
    F4AACgkQC4fpRGXEptfwQAP/T1ZhSzX4PuQloL2o4ZJ4OJvSoQtye/hWwHpwGMHnc8QKThLz
    3r8qOFNsJtJTd9c7w/2lyeeJWDWbNSzCQA91xcIu2xO/5Bdi/izuqmNQlfdS8b1KQYzNhRUB
    mtsAjsEMlycuCmB4P6H1COQXf75RMDvwk0agvyUjpwWgr6oqSas=
    =x93a
    -----END PGP PUBLIC KEY BLOCK-----
- source: "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main"
  key: |
    -----BEGIN PGP PUBLIC KEY BLOCK-----
    Version: GnuPG v1.4.12 (GNU/Linux)

    mQINBE6XR8IBEACVdDKT2HEH1IyHzXkb4nIWAY7echjRxo7MTcj4vbXAyBKOfjja
    UrBEJWHN6fjKJXOYWXHLIYg0hOGeW9qcSiaa1/rYIbOzjfGfhE4x0Y+NJHS1db0V
    G6GUj3qXaeyqIJGS2z7m0Thy4Lgr/LpZlZ78Nf1fliSzBlMo1sV7PpP/7zUO+aA4
    bKa8Rio3weMXQOZgclzgeSdqtwKnyKTQdXY5MkH1QXyFIk1nTfWwyqpJjHlgtwMi
    c2cxjqG5nnV9rIYlTTjYG6RBglq0SmzF/raBnF4Lwjxq4qRqvRllBXdFu5+2pMfC
    IZ10HPRdqDCTN60DUix+BTzBUT30NzaLhZbOMT5RvQtvTVgWpeIn20i2NrPWNCUh
    hj490dKDLpK/v+A5/i8zPvN4c6MkDHi1FZfaoz3863dylUBR3Ip26oM0hHXf4/2U
    A/oA4pCl2W0hc4aNtozjKHkVjRx5Q8/hVYu+39csFWxo6YSB/KgIEw+0W8DiTII3
    RQj/OlD68ZDmGLyQPiJvaEtY9fDrcSpI0Esm0i4sjkNbuuh0Cvwwwqo5EF1zfkVj
    Tqz2REYQGMJGc5LUbIpk5sMHo1HWV038TWxlDRwtOdzw08zQA6BeWe9FOokRPeR2
    AqhyaJJwOZJodKZ76S+LDwFkTLzEKnYPCzkoRwLrEdNt1M7wQBThnC5z6wARAQAB
    tBxQb3N0Z3JlU1FMIERlYmlhbiBSZXBvc2l0b3J5iQI9BBMBCAAnAhsDBQsJCAcD
    BRUKCQgLBRYCAwEAAh4BAheABQJRKm2VBQkINsBBAAoJEH/MfUaszEz4RTEP/1sQ
    HyjHaUiAPaCAv8jw/3SaWP/g8qLjpY6ROjLnDMvwKwRAoxUwcIv4/TWDOMpwJN+C
    JIbjXsXNYvf9OX+UTOvq4iwi4ADrAAw2xw+Jomc6EsYla+hkN2FzGzhpXfZFfUsu
    phjY3FKL+4hXH+R8ucNwIz3yrkfc17MMn8yFNWFzm4omU9/JeeaafwUoLxlULL2z
    Y7H3+QmxCl0u6t8VvlszdEFhemLHzVYRY0Ro/ISrR78CnANNsMIy3i11U5uvdeWV
    CoWV1BXNLzOD4+BIDbMB/Do8PQCWiliSGZi8lvmj/sKbumMFQonMQWOfQswTtqTy
    Q3yhUM1LaxK5PYq13rggi3rA8oq8SYb/KNCQL5pzACji4TRVK0kNpvtxJxe84X8+
    9IB1vhBvF/Ji/xDd/3VDNPY+k1a47cON0S8Qc8DA3mq4hRfcgvuWy7ZxoMY7AfSJ
    Ohleb9+PzRBBn9agYgMxZg1RUWZazQ5KuoJqbxpwOYVFja/stItNS4xsmi0lh2I4
    MNlBEDqnFLUxSvTDc22c3uJlWhzBM/f2jH19uUeqm4jaggob3iJvJmK+Q7Ns3Wcf
    huWwCnc1+58diFAMRUCRBPeFS0qd56QGk1r97B6+3UfLUslCfaaA8IMOFvQSHJwD
    O87xWGyxeRTYIIP9up4xwgje9LB7fMxsSkCDTHOkiEYEEBEIAAYFAk6XSO4ACgkQ
    xa93SlhRC1qmjwCg9U7U+XN7Gc/dhY/eymJqmzUGT/gAn0guvoX75Y+BsZlI6dWn
    qaFU6N8HiQIcBBABCAAGBQJOl0kLAAoJEExaa6sS0qeuBfEP/3AnLrcKx+dFKERX
    o4NBCGWr+i1CnowupKS3rm2xLbmiB969szG5TxnOIvnjECqPz6skK3HkV3jTZaju
    v3sR6M2ItpnrncWuiLnYcCSDp9TEMpCWzTEgtrBlKdVuTNTeRGILeIcvqoZX5w+u
    i0eBvvbeRbHEyUsvOEnYjrqoAjqUJj5FUZtR1+V9fnZp8zDgpOSxx0LomnFdKnhj
    uyXAQlRCA6/roVNR9ruRjxTR5ubteZ9ubTsVYr2/eMYOjQ46LhAgR+3Alblu/WHB
    MR/9F9//RuOa43R5Sjx9TiFCYol+Ozk8XRt3QGweEH51YkSYY3oRbHBb2Fkql6N6
    YFqlLBL7/aiWnNmRDEs/cdpo9HpFsbjOv4RlsSXQfvvfOayHpT5nO1UQFzoyMVpJ
    615zwmQDJT5Qy7uvr2eQYRV9AXt8t/H+xjQsRZCc5YVmeAo91qIzI/tA2gtXik49
    6yeziZbfUvcZzuzjjxFExss4DSAwMgorvBeIbiz2k2qXukbqcTjB2XqAlZasd6Ll
    nLXpQdqDV3McYkP/MvttWh3w+J/woiBcA7yEI5e3YJk97uS6+ssbqLEd0CcdT+qz
    +Waw0z/ZIU99Lfh2Qm77OT6vr//Zulw5ovjZVO2boRIcve7S97gQ4KC+G/+QaRS+
    VPZ67j5UMxqtT/Y4+NHcQGgwF/1i
    =Iugu
    -----END PGP PUBLIC KEY BLOCK-----
