#cloud-config

# $ aws --profile production ec2 run-instances --user-data file://nginx.yml --security-groups "ssh-http-https" --image-id ami-5189a661 --instance-type t2.medium --region us-west-2 --network-interfaces '[{"DeviceIndex":1,"NetworkInterfaceId":"eni-9fbe3dc4"},{"DeviceIndex":2,"NetworkInterfaceId":"eni-f1bf3caa"}]'
# Must copy private ssl keys manually to /etc/nginx/ssl/*/server.key then restart nginx.
# Choose instance size based on network performance required.

apt_sources:
- source: ppa:nginx/stable

bootcmd:
- cloud-init-per once ssh-users-ca echo "TrustedUserCAKeys /etc/ssh/users_ca.pub" >> /etc/ssh/sshd_config

output:
  all: '| tee -a /var/log/cloud-init-output.log'

package_upgrade: true

packages:
- curl
- dnsmasq
- nginx-full
- ntp
- unattended-upgrades
- update-notifier-common

power_state:
  mode: reboot

runcmd:
- mkdir -p /etc/nginx/ssl
#- tar -zxf ssl.tgz --directory /etc/nginx/ssl
# Generate a new (takes a few minutes.)
- openssl dhparam 2048 -out /etc/nginx/ssl/dhparam.pem
- chmod 600 /etc/nginx/ssl/dhparam.pem
- curl -o /etc/nginx/nginx.conf https://raw.githubusercontent.com/ENCODE-DCC/encoded/master/encode-proxy-nginx.conf
- sed -i.bak s/171.67.205./172.31.0./g /etc/nginx/nginx.conf

write_files:
- path: /etc/apt/apt.conf.d/20auto-upgrades
  content: |
    APT::Periodic::Update-Package-Lists "1";
    APT::Periodic::Unattended-Upgrade "1";

- path: /etc/apt/apt.conf.d/50unattended-upgrades
  content: |
    Unattended-Upgrade::Allowed-Origins {
        "${distro_id} ${distro_codename}-security";
    };
    Unattended-Upgrade::Automatic-Reboot "true";

- path: /etc/network/interfaces.d/eth1.cfg
  content: |
    auto eth1
    iface eth1 inet dhcp
      post-up ip rule add from 172.31.0.70 lookup 201
      post-up ip route add default via 172.31.0.1 dev eth1 table 201

- path: /etc/network/interfaces.d/eth2.cfg
  content: |
    auto eth2
    iface eth2 inet dhcp
      post-up ip rule add from 172.31.0.78 lookup 202
      post-up ip route add default via 172.31.0.1 dev eth2 table 202

- path: /etc/motd
  content: |
    #########################################
    ##         Nginx proxy server          ##
    ##  For demo instances:                ##
    ##  ssh <name>.instance.encodedcc.org  ##
    #########################################

- path: /etc/ssh/users_ca.pub
  content: ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAv/ymOcnN4LhM4NACc3Or116XXJ6KytuOgB/+1qNkOFBqBosrn7cmJ35rsoNHRgYNrCsRE9ch74RKsN6H72FtSJgBhGh/9oUK7Os6Fqt3/ZZXxgxIx6ubs/MTgrxrAnujiBxUXMXQhLKMriNMpo8mt4nGYVtLk9PBjiyfncaS8H9ZKoNio9dhP8bmTuYvioAI35dqKdSlVLyzr/XkZxia8Ki+pQ0N6uuiEwMR3ToM+LSp8wpFOOAiu4PEAujRW7us/+1hlpKWfn0J7/V3826joHE+I967Vg/+ikcVhF77JjK1nib879VgCWfmn1HPQosIpk4yJfVgGvRVI7I2nfBPVw== encoded@demo-l.encodedcc.org
