#!/bin/bash -f

aws_account=
do_help=
do_debug=
creds_file=$HOME/.aws_test/test_creds.sh

if [ -f "${creds_file}" ]; then
  # Default the values of these variables by peeking in the test_creds.sh script
  aws_account=`grep 'export ACCOUNT_NUMBER=' ${creds_file} | sed -E 's|^export ACCOUNT_NUMBER=(.*)$|\1|'`
fi

while [ $# -gt 0 ]; do
  if [ "$1" = "--aws_account" ]; then
    aws_account=$2
    shift 2
  elif [ "$1" = "--help" ]; then
    do_help=TRUE
    echo "EXPLICIT --help"
    shift 1
  elif [ "$1" = "--debug" ]; then
    do_debug=TRUE
    shift 1
  else
    do_help=TRUE
    echo "ELSE CLAUSE"
    break
  fi
done

if [ -n "${do_help}" ]; then
  echo "Syntax: $0 { --aws_account <account> | --debug | --help }"
  echo ""
  echo " This will execute 'make ecr-login AWS_ACCOUNT=<account>'."
  echo " If --debug is given, additional instrumentation output will happen as it goes."
  echo " If unspecified, <account> defaults to '${aws_account}' (from 'export ACCOUNT_NUMBER=...' in ${creds_file})."
  if [ ! -f "${creds_file}" ]; then
    echo " NOTE: The file ${creds_file} does not exist."
  fi
  echo ""
  exit 1
fi

if [ -n "${do_debug}" ]; then
  echo "Using settings from ${creds_file} ..."
fi

. ${creds_file}

if [ "${aws_account}" != "${ACCOUNT_NUMBER}" ]; then
    echo "Data mismatch. \$aws_account='${aws_account}' but \$ACCOUNT_NUMBER='${ACCOUNT_NUMBER}'."
    exit 1
fi

if [ -n "${do_debug}" ]; then
  echo "Credentials for ACCESS_KEY_ID='...${AWS_ACCESS_KEY_ID:15}' will be used for ecr-login."
fi

make ecr-login AWS_ACCOUNT="${aws_account}"
