# Action that Runs Cypress Tests

name: Cypress Tests - Data

# Controls when the action will run.
on:
  schedule:
    - cron: '0 5 * * 1-5'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cypress-run:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false  # suggested by Cypress
      matrix:
        containers: [1, 2, 3, 4, 5]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Runs a set of commands using the runners shell
      - name: Install
        run: |
          npm --version
          npm config set python /usr/bin/python3.8
          npm ci
          $(npm bin)/cypress install

      - name: Cypress
        env:
          CYPRESS_KEY: ${{ secrets.CYPRESS_KEY }}
          Auth0Client: ${{ secrets.Auth0Client }}
          Auth0Secret: ${{ secrets.Auth0Secret }}
        run: |
         $(npm bin)/cypress run --record --key $CYPRESS_KEY --env Auth0Client=$Auth0Client,Auth0Secret=$Auth0Secret --project ./deploy/post_deploy_testing --browser chrome --config baseUrl=https://data.4dnucleome.org/ --parallel 
