# Action that Runs Cypress Tests

name: Cypress Tests - Data

# Controls when the action will run.
on:
  schedule:
    - cron: '0 5 * * 1-5'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  install:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Cache npm and Cypress
      #   uses: actions/cache@v4
      #   with:
      #     path: |
      #       ~/.cache/Cypress
      #       node_modules
      #     key: my-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install Cypress
        run: |
          npm ci
          npm i cypress

  cypress-run:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    needs: install
    strategy:
      fail-fast: false  # suggested by Cypress
      matrix:
        containers: [1, 2, 3, 4, 5]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          project: ./deploy/post_deploy_testing
          record: true
          browser: chrome
          parallel: true
          config: baseUrl=https://data.4dnucleome.org/
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_KEY }}
          CYPRESS_Auth0Client: ${{ secrets.Auth0Client }}
          CYPRESS_Auth0Secret: ${{ secrets.Auth0Secret }}
